backend:
  name: github
  repo: tripurari001/testing-netlify
  site_domain: frosty-payne-06cd67.netlify.com
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: 'hero'
    label: 'Hero Section'
    folder: 'content/hero'
    create: false
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: ''
    editor:
      preview: false
    fields:
      - { label: 'Heading', name: 'heading', widget: 'string' }
      - { label: 'Sub Heading', name: 'subheading', widget: 'string' }